WebProject001/Controllers/ShopsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebProject001.Models;

namespace WebProject001.Controllers
{
    public class ShopsController : Controller
    {
        private readonly Context _context;

        public ShopsController(Context context)
        {
            _context = context;
        }

        // GET: Shops
        public async Task<IActionResult> Index(
            string sortOrder,
            string currentFilter,
            string searchShopName,
            int? pageNumber
        )
        {
            int pageSize = 5;
            ViewData["CurrentSort"] = sortOrder;
            ViewData["SortByShopName"] = (sortOrder == "shopName_asc") ? "shopName_desc" : "shopName_asc";
            ViewData["CurrentShopName"] = searchShopName;
            if (searchShopName != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchShopName = currentFilter;
            }
            ViewData["CurrentFilter"] = searchShopName;

            var result = from x in _context.Shops select x;
            if (!String.IsNullOrEmpty(searchShopName))
            {
                result = result.Where(u => u.ShopName.Contains(searchShopName));
            }

            switch (sortOrder)
            {
                case "shopName_desc":
                    result = result.OrderByDescending(f => f.ShopName);
                    break;
                default:
                    result = result.OrderBy(f => f.ShopName);
                    break;
            }
            return View(await PaginatedList<Shop>.CreateAsync(result.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        // GET: Shops/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shop = await _context.Shops
                .FirstOrDefaultAsync(m => m.Id == id);
            if (shop == null)
            {
                return NotFound();
            }

            return View(shop);
        }

        // GET: Shops/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Shops/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ShopName,AddressLine,City")] Shop shop)
        {
            if (ModelState.IsValid)
            {
                _context.Add(shop);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(shop);
        }

        // GET: Shops/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shop = await _context.Shops.FindAsync(id);
            if (shop == null)
            {
                return NotFound();
            }
            return View(shop);
        }

        // POST: Shops/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ShopName,AddressLine,City")] Shop shop)
        {
            if (id != shop.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(shop);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShopExists(shop.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(shop);
        }

        // GET: Shops/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shop = await _context.Shops
                .FirstOrDefaultAsync(m => m.Id == id);
            if (shop == null)
            {
                return NotFound();
            }

            return View(shop);
        }

        // POST: Shops/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var shop = await _context.Shops.FindAsync(id);
            if (shop != null)
            {
                _context.Shops.Remove(shop);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ShopExists(int id)
        {
            return _context.Shops.Any(e => e.Id == id);
        }
    }
}

WebProject001/Controllers/StatsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using WebProject001.Models;
using WebProject001.ViewModels;

namespace WebProject001.Controllers
{
    public class StatsController : Controller
    {
        private readonly Context _context;

        public StatsController(Context context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ExpendituresByYearMonth()
        {
            var result = _context.Expenditures
                .GroupBy(x => _context.GetYearMonth(x.ExpenditureDate))
                .Select(
                    y => new ExpenditureByYearMonth
                    {
                        YearMonth = _context.GetYearMonth(y.First().ExpenditureDate),
                        Total = y.Sum(c => Math.Round(c.Price * c.Quantity, 2))
                    }
                );
            return View(result);
        }

        [HttpGet]
        public IActionResult ExpendituresByExpeditureFilterByYearMonth()
        {
            var listYearMonth = _context.Expenditures
                .GroupBy(a => _context.GetYearMonth(a.ExpenditureDate))
                .Select(
                    b => new YearMonthVM
                    {
                        YearMonth = _context.GetYearMonth(b.First().ExpenditureDate)
                    }
                );
            ViewData["YearMonth"] = new SelectList(listYearMonth, "YearMonth", "YearMonth");

            string criteria = (listYearMonth.ToList())[0].YearMonth;

            ViewData["Criteria"] = criteria;

            var result = _context.Expenditures
                .Where(o => _context.GetYearMonth(o.ExpenditureDate) == criteria)
                .GroupBy(p => p.ExpenditureName)
                .Select(
                    q => new ExpenditureByExpenditure
                    {
                        ExpenditureName = q.First().ExpenditureName,
                        Total = q.Sum(r => Math.Round(r.Price * r.Quantity, 2))
                    }
                );
            return View(result);
        }

        [HttpPost]
        public IActionResult ExpendituresByExpeditureFilterByYearMonth(string yearMonth)
        {
            var listYearMonth = _context.Expenditures
                .GroupBy(a => _context.GetYearMonth(a.ExpenditureDate))
                .Select(
                    b => new YearMonthVM
                    {
                        YearMonth = _context.GetYearMonth(b.First().ExpenditureDate)
                    }
                );
            ViewData["YearMonth"] = new SelectList(listYearMonth, "YearMonth", "YearMonth", yearMonth);

            string criteria = yearMonth;

            ViewData["Criteria"] = criteria;

            var result = _context.Expenditures
                .Where(o => _context.GetYearMonth(o.ExpenditureDate) == criteria)
                .GroupBy(p => p.ExpenditureName)
                .Select(
                    q => new ExpenditureByExpenditure
                    {
                        ExpenditureName = q.First().ExpenditureName,
                        Total = q.Sum(r => Math.Round(r.Price * r.Quantity, 2))
                    }
                );
            return View(result);
        }

        [HttpGet]
        public IActionResult ExpendituresByCategoryFilterByYearMonth()
        {
            var listYearMonth = _context.Expenditures
                .GroupBy(a => _context.GetYearMonth(a.ExpenditureDate))
                .Select(
                    b => new YearMonthVM
                    {
                        YearMonth = _context.GetYearMonth(b.First().ExpenditureDate)
                    }
                );
            ViewData["YearMonth"] = new SelectList(listYearMonth, "YearMonth", "YearMonth");

            string criteria = (listYearMonth.ToList())[0].YearMonth;

            ViewData["Criteria"] = criteria;

            var result = _context.Expenditures.Include(n => n.Category)
                .Where(o => _context.GetYearMonth(o.ExpenditureDate) == criteria)
                .GroupBy(p => p.Category.CategoryName)
                .Select(
                    q => new ExpenditureByCategory
                    {
                        CategoryName = q.First().Category.CategoryName,
                        Total = q.Sum(r => Math.Round(r.Price * r.Quantity, 2))
                    }
                );
            return View(result);
        }

        [HttpPost]
        public IActionResult ExpendituresByCategoryFilterByYearMonth(string yearMonth)
        {
            var listYearMonth = _context.Expenditures
                .GroupBy(a => _context.GetYearMonth(a.ExpenditureDate))
                .Select(
                    b => new YearMonthVM
                    {
                        YearMonth = _context.GetYearMonth(b.First().ExpenditureDate)
                    }
                );
            ViewData["YearMonth"] = new SelectList(listYearMonth, "YearMonth", "YearMonth", yearMonth);

            string criteria = yearMonth;

            ViewData["Criteria"] = criteria;

            var result = _context.Expenditures.Include(n => n.Category)
                .Where(o => _context.GetYearMonth(o.ExpenditureDate) == criteria)
                .GroupBy(p => p.Category.CategoryName)
                .Select(
                    q => new ExpenditureByCategory
                    {
                        CategoryName = q.First().Category.CategoryName,
                        Total = q.Sum(r => Math.Round(r.Price * r.Quantity, 2))
                    }
                );
            return View(result);
        }

        [HttpGet]
        public IActionResult ExpendituresByShopFilterByYearMonth()
        {
            var listYearMonth = _context.Expenditures
                .GroupBy(a => _context.GetYearMonth(a.ExpenditureDate))
                .Select(
                    b => new YearMonthVM
                    {
                        YearMonth = _context.GetYearMonth(b.First().ExpenditureDate)
                    }
                );
            ViewData["YearMonth"] = new SelectList(listYearMonth, "YearMonth", "YearMonth");

            string criteria = (listYearMonth.ToList())[0].YearMonth;

            ViewData["Criteria"] = criteria;

            var result = _context.Expenditures.Include(n => n.Category)
                .Where(o => _context.GetYearMonth(o.ExpenditureDate) == criteria)
                .GroupBy(p => p.Shop.ShopName)
                .Select(
                    q => new ExpenditureByShop
                    {
                        ShopName = q.First().Shop.ShopName,
                        Total = q.Sum(r => Math.Round(r.Price * r.Quantity, 2))
                    }
                );
            return View(result);
        }

        [HttpPost]
        public IActionResult ExpendituresByShopFilterByYearMonth(string yearMonth)
        {
            var listYearMonth = _context.Expenditures
                .GroupBy(a => _context.GetYearMonth(a.ExpenditureDate))
                .Select(
                    b => new YearMonthVM
                    {
                        YearMonth = _context.GetYearMonth(b.First().ExpenditureDate)
                    }
                );
            ViewData["YearMonth"] = new SelectList(listYearMonth, "YearMonth", "YearMonth", yearMonth);

            string criteria = yearMonth;

            ViewData["Criteria"] = criteria;

            var result = _context.Expenditures.Include(n => n.Category)
                .Where(o => _context.GetYearMonth(o.ExpenditureDate) == criteria)
                .GroupBy(p => p.Shop.ShopName)
                .Select(
                    q => new ExpenditureByShop
                    {
                        ShopName = q.First().Shop.ShopName,
                        Total = q.Sum(r => Math.Round(r.Price * r.Quantity, 2))
                    }
                );
            return View(result);
        }

        // ====
        [HttpGet]
        public IActionResult ExpendituresByPaymentMethodFilterByYearMonth()
        {
            var listYearMonth = _context.Expenditures
                .GroupBy(a => _context.GetYearMonth(a.ExpenditureDate))
                .Select(
                    b => new YearMonthVM
                    {
                        YearMonth = _context.GetYearMonth(b.First().ExpenditureDate)
                    }
                );
            ViewData["YearMonth"] = new SelectList(listYearMonth, "YearMonth", "YearMonth");

            string criteria = (listYearMonth.ToList())[0].YearMonth;

            ViewData["Criteria"] = criteria;

            var result = _context.Expenditures.Include(n => n.Category)
                .Where(o => _context.GetYearMonth(o.ExpenditureDate) == criteria)
                .GroupBy(p => p.PaymentMethod.Name)
                .Select(
                    q => new ExpenditureByPaymentMethod
                    {
                        PaymentMethodName = q.First().PaymentMethod.Name,
                        Total = q.Sum(r => Math.Round(r.Price * r.Quantity, 2))
                    }
                );
            return View(result);
        }

        [HttpPost]
        public IActionResult ExpendituresByPaymentMethodFilterByYearMonth(string yearMonth)
        {
            var listYearMonth = _context.Expenditures
                .GroupBy(a => _context.GetYearMonth(a.ExpenditureDate))
                .Select(
                    b => new YearMonthVM
                    {
                        YearMonth = _context.GetYearMonth(b.First().ExpenditureDate)
                    }
                );
            ViewData["YearMonth"] = new SelectList(listYearMonth, "YearMonth", "YearMonth", yearMonth);

            string criteria = yearMonth;

            ViewData["Criteria"] = criteria;

WebProject001/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebProject001</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebProject001.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/apexcharts.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <img src="~/images/money.png" style="width:50px; height:50px; border-radius: 50%;">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-house"></i> Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-info" asp-area="" asp-controller="Categories" asp-action="Index"><i class="bi bi-bookmark"></i> Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-info" asp-area="" asp-controller="Shops" asp-action="Index"><i class="bi bi-shop-window"></i> Shops</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-info" asp-area="" asp-controller="PaymentMethods" asp-action="Index"><i class="bi bi-wallet"></i> Payment Methods</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-info" asp-area="" asp-controller="Expenditures" asp-action="Index"><i class="bi bi-coin"></i> Expenditures</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-info" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="bi bi-question-circle"></i> Stats
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <li><a class="dropdown-item text-info" asp-controller="Stats" asp-action="ExpendituresByYearMonth">Expenditures by year and month</a></li>
                                <li><a class="dropdown-item text-info" asp-controller="Stats" asp-action="ExpendituresByExpeditureFilterByYearMonth">Expenditures by Expediture Name filter by Year & Month</a></li>
                                <li><a class="dropdown-item text-info" asp-controller="Stats" asp-action="ExpendituresByCategoryFilterByYearMonth">Expenditures by Category Name filter by Year & Month</a></li>
                                <li><a class="dropdown-item text-info" asp-controller="Stats" asp-action="ExpendituresByShopFilterByYearMonth">Expenditures by Shop Name filter by Year & Month</a></li>
                                <li><a class="dropdown-item text-info" asp-controller="Stats" asp-action="ExpendituresByPaymentMethodFilterByYearMonth">Expenditures by Payment Method Name filter by Year & Month</a></li>
                                <li><hr /></li>
                                <li><a class="dropdown-item text-info" asp-controller="Stats" asp-action="ExpendituresByYearMonthChart">Expenditures by year and month - column chart</a></li>
                                <li><a class="dropdown-item text-info" asp-controller="Stats" asp-action="ExpendituresByExpeditureFilterByYearMonthChart">Expenditures by Expediture Name filter by Year & Month - column chart</a></li>
                                <li><a class="dropdown-item text-info" asp-controller="Stats" asp-action="ExpendituresByCategoryFilterByYearMonthChart">Expenditures by Category Name filter by Year & Month - column chart</a></li>
                                <li><a class="dropdown-item text-info" asp-controller="Stats" asp-action="ExpendituresByShopFilterByYearMonthChart">Expenditures by Shop Name filter by Year & Month - column chart</a></li>
                                <li><a class="dropdown-item text-info" asp-controller="Stats" asp-action="ExpendituresByPaymentMethodFilterByYearMonthChart">Expenditures by Payment Method Name filter by Year & Month - column chart</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2024 - Expenditures by Grzegorz Plak
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>